### ISSUE TITLE
Combine b64?

### ISSUE THREAD

**Issue by nicolasdelfino** [lukechilds/merge-images#27]
Hi Luke, thanks for a great lib!
This is more a question than an issue so feel free to close it right away:
I was wondering if this would allow me to combine two data URI into 1?

The use case being a drawing / animation application where I need to combine each animation frame's different layers into one frame.

/Nicolas

**Comment by lukechilds** [comment]
It sure will, it works with any valid image source: https://github.com/lukechilds/merge-images#images

Similar example here: https://github.com/lukechilds/merge-images/issues/7

Good luck with your project 👍

**Comment by nicolasdelfino** [comment]
Awesome! thanks for your quick reply @lukechilds ! 

So I would be doing something like this? 
```javascript
const a = 'data:image/png;base64,blublublu==';
const b = 'data:image/png;base64,blablabla==';
mergeImages([a, b]).then(b64 => {
   //do something with b64
});
```

**Comment by lukechilds** [comment]
Yup

**Comment by nicolasdelfino** [comment]
Darn it, so close, seems like I can't get it to work with react native. Guess I'm getting this cause there is no window: error in combining data TypeError: Cannot read property 'createElement' of undefined.

You think using the node variant would help @lukechilds ?

**Comment by lukechilds** [comment]
I don't think so, React Native isn't Node.js so I doubt `node-canvas` will work.

You may be able to get it working with something like this https://github.com/iddan/react-native-canvas although you might need to fork.

**Comment by alexgnatrow** [comment]
I simply did same as @nicolasdelfino wrote

`mergeImages(arr, { Canvas: Canvas })
          .then(b64 => {`

 and this is what I am getting:

`Error: Couldn't load image
  at img.onerror (/var/www/dev.wupwoo.com/chatServer/node_modules/merge-images/dist/index.umd.js:40:45)
 at Image.src (/var/www/dev.wupwoo.com/chatServer/node_modules/canvas/lib/image.js:28:17)
at /var/www/dev.wupwoo.com/chatServer/node_modules/merge-images/dist/index.umd.js:42:11
at new Promise (<anonymous>)
at /var/www/dev.wupwoo.com/chatServer/node_modules/merge-images/dist/index.umd.js:32:54
at Array.map (<anonymous>)
at /var/www/dev.wupwoo.com/chatServer/node_modules/merge-images/dist/index.umd.js:32:23
at new Promise (<anonymous>)
at mergeImages (/var/www/dev.wupwoo.com/chatServer/node_modules/merge-images/dist/index.umd.js:21:9)
`

Here is my array:

`arr = [ 'data:image/svg+xml;base64,L3Zhci93d3cvZGV2Lnd1cHdvby5jb20vd3d3L3d1cHVfYXBpL3N2Zy9hdmF0YXIvRmVtYWxlL2JhY2toYWlyL3JlZC9mX2hiX3JkXzA1LnN2Zw==',
'data:image/svg+xml;base64,L3Zhci93d3cvZGV2Lnd1cHdvby5jb20vd3d3L3d1cHVfYXBpL3N2Zy9hdmF0YXIvRmVtYWxlL2Vhci9vbGl2ZS9mX29sX2Vhcl8wMi5zdmc=',
 'data:image/svg+xml;base64,L3Zhci93d3cvZGV2Lnd1cHdvby5jb20vd3d3L3d1cHVfYXBpL3N2Zy9hdmF0YXIvRmVtYWxlL2hlYWQvb2xpdmUvZl9vbF9oZF8wNC5zdmc=',
'data:image/svg+xml;base64,L3Zhci93d3cvZGV2Lnd1cHdvby5jb20vd3d3L3d1cHVfYXBpL3N2Zy9hdmF0YXIvRmVtYWxlL2V5ZWJyb3cvYnJvd24vZl9ibl9leWViXzAzLnN2Zw==',
'data:image/svg+xml;base64,L3Zhci93d3cvZGV2Lnd1cHdvby5jb20vd3d3L3d1cHVfYXBpL3N2Zy9hdmF0YXIvRmVtYWxlL2V5ZS9ncmVlbi9mX2duX2V5ZV8wMi5zdmc=',
'data:image/svg+xml;base64,L3Zhci93d3cvZGV2Lnd1cHdvby5jb20vd3d3L3d1cHVfYXBpL3N2Zy9hdmF0YXIvRmVtYWxlL25vc2Uvb2xpdmUvZl9vbF9ub3NlXzAxLnN2Zw==',
'data:image/svg+xml;base64,L3Zhci93d3cvZGV2Lnd1cHdvby5jb20vd3d3L3d1cHVfYXBpL3N2Zy9hdmF0YXIvRmVtYWxlL21vdXRoL2ZfbXRoXzExLnN2Zw==',
'data:image/svg+xml;base64,L3Zhci93d3cvZGV2Lnd1cHdvby5jb20vd3d3L3d1cHVfYXBpL3N2Zy9hdmF0YXIvRmVtYWxlL2hhaXIvcmVkL2ZfaGZfcmRfMDUuc3Zn',
'data:image/svg+xml;base64,L3Zhci93d3cvZGV2Lnd1cHdvby5jb20vd3d3L3d1cHVfYXBpL3N2Zy9hdmF0YXIvRmVtYWxlL2dsYXNzZXMvZl9nbGFzXzAzLnN2Zw==' ]`
