### ISSUE TITLE
Is calling mergeImages inside Google Maps ImageMapType getTileUrl possible?

### ISSUE THREAD

**Issue by ripern** [lukechilds/merge-images#28]
This is definitely not a bug, but I'd like to understand if this library somehow could be used in this scenario?
The code below *does not work*, but rather gives the error
GET http://localhost:3000/[object%20Promise] 404 (Not Found)

`_addOverLay: function () {
        this.overlayLayer = new google.maps.ImageMapType({
            getTileUrl: function (tile, zoom) {
                return mergeImages(['/a.png', '/b.png']).then(b64 => {
                    return b64
                })
             },
             tileSize: new google.maps.Size(256, 256)
        });    
        
        this.gMap.overlayMapTypes.insertAt(0, this.overlayLayer);
    },`

a.png and b.png are just examples here, they will later be dynamically assigned so moving the mergeImages call outside of getTileUrl is not an option for me. I've tried the same using async/await with the same outcome. I'm guessing getTileUrl can't handle an async call inside it, or am I doing something clearly wrong with the promise?

**Comment by lukechilds** [comment]
You're returning a promise from a function that your code is expecting to return a string.

You need to either call `mergeImages()` first and the return the resolved value from `getTileUrl()` or refactor your code to allow `getTileUrl()` to return a Promise. Those are your only options.
