### ISSUE TITLE
Can't find Python executable "c:\Python\27\python.exe", you can set the PYTHON env variable.

### ISSUE THREAD

**Issue by sonipreshita** [lukechilds/merge-images#44]
I have downloaded and set environment variable. still it gives me error

**Comment by lukechilds** [comment]
That shouldn't be anything to do with `merge-images`, it doesn't use Python for anything. Most likely an issue with your environment or possibly the Node.js `canvas`?

Closing this as I'm pretty sure it's unrelated but feel free to re-open if you find evidence to suggest otherwise.
