### ISSUE TITLE
Provide a way to rotate images

### ISSUE THREAD

**Issue by astronomersiva** [lukechilds/merge-images#45]
Thanks for writing such an easy to use tool to merge images! It would be very useful if there was a way to rotate the input images.

**Comment by lukechilds** [comment]
Thanks, for the suggestion.

I think that may be slightly beyond the scope of this module. It's just supposed to merge images together, if you need opacity or other transformations they should be already applied.

However, if this can be implemented simply without too much code bloat, I would be happy to accept a PR for this.

**Comment by astronomersiva** [comment]
I looked into this @lukechilds and I feel it's better to handle this outside of merge-images itself. There's already a [package](https://github.com/nathan7/rotate-image/blob/master/index.js) for this and implementing this here would pretty much involve the same code.

Thanks for your time and this awesome package!
