### ISSUE TITLE
Optional image crossOrigin="anonymous";

### ISSUE THREAD

**Issue by svarunan** [lukechilds/merge-images#54]
Please give an option to set crossOrigin attribute for the source images.

This is solve the problem while converting canvas to b64
**"Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported."**

**Comment by xcompile** [comment]
using it with polymer 3, run into the same problem even when deploying the application with a standard HTTP server.

**Comment by isaac-martin** [comment]
Also running into this issue. Images being served of CDN. any update?

**Comment by dongseup** [comment]
Importing images to CDn
Unable to retrieve image.
CrossOrgin = 'Anonymous'
Please insert it.

**Comment by donmb1** [comment]
+1
Anyone came up with a solution?

**Comment by trevorblades** [comment]
@dongseup @donmb1 @svarunan I made a PR (#82) that solves this issue by adding a `crossOrigin` option that can be set to `Anonymous` to facilitate cross-origin image merging! 🎉

**Comment by lukechilds** [comment]
#82 is now merged and published as `merge-images@1.2.0`.
