### ISSUE TITLE
Not working nodejs

### ISSUE THREAD

**Issue by narayanachitrakars** [lukechilds/merge-images#55]
I have created the node app and here is my API 

app.get('/',function(req,res){
       mergeImages(['./public/images/T_4.gif','./public/images/e2.jpg'], {
      Canvas: Canvas
    })
      .then((b64) => { console.log("hi")});
  })

1. After running the App , the function mergeImages is called and invoking indexjs in the back ground , but i am getting window is undefined in indexjs i.e
var canvas = options.Canvas ? new options.Canvas() : window.document.createElement('canvas'); 

2.So i removed that line and set  var canvas = options.Canvas  now i am getting
error at  var ctx = canvas[0].getContext('2d'); i.e  getContext function is undefined.

Is this an issue with nodejs or this module is used only for client side scripting ? Please help me to fix the issue.

Thanks

**Comment by Splash-22557** [comment]
So uh, if the problem is solved. Why don't you show the solution to help others who may come across the issue?

**Comment by lukechilds** [comment]
@narayanachitrakars Are you able to elaborate on how you fixed the issue?

**Comment by NeXTs** [comment]
For those who gets "window is undefined" error, make sure you are using exactly node.js version, you must provide Canvas manually https://github.com/lukechilds/merge-images#nodejs-usage

**Comment by lukechilds** [comment]
Thanks @NeXTs
