### ISSUE TITLE
question using html? works somewhat on chrome, not at all on safari...

### ISSUE THREAD

**Issue by zahachtah** [lukechilds/merge-images#59]
Hi, sorry to bother... I need to display images I produce in julia from tiles and this library seemed great but I am not fluent in javascript. in chrome I get an image but they seem to be overlaid. on safari I get tainted canvas error.... Do you have any suggestion for making this work?:

<!DOCTYPE html>
<meta charset="utf-8">

<body>
    <img crossOrigin="Anonymous"/></img>

<script src="https://unpkg.com/merge-images"></script>
<script>

mergeImages([
             { src: 'https://tile.openstreetmap.org/7/63/42.png', x: 0, y: 0 },
             { src: 'https://tile.openstreetmap.org/7/64/42.png', x: 256, y: 0 },
             { src: 'https://tile.openstreetmap.org/7/64/43.png', x: 254, y: 256 },
             { src: 'https://tile.openstreetmap.org/7/63/43.png', x: 0, y: 256 }
             ])
             .then(b64 => document.querySelector('img').src = b64);
</script>
</body>

**Comment by lukechilds** [comment]
Probably a permission error reading untrusted data into the canvas context.
