### ISSUE TITLE
Anyway To Make Rows And Columns?

### ISSUE THREAD

**Issue by M4Artz** [lukechilds/merge-images#71]
Just Wondering If There Is Anyway To Make Rows And Columns? Would Really Help Me!

**Comment by lukechilds** [comment]
Sorry, I'm not too sure what you're asking? What do you mean by rows and columns?

**Comment by M4Artz** [comment]
Like For Example I Have 9 100x100 Images Could I Make It When I Merge The Images 3 Down And 3 Wide

**Comment by M4Artz** [comment]
Like this for example https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS-0ur9hgxa1m1gDv525JnbbTcNFz53pXt9WMZb5pSIquKwZbVW

**Comment by lukechilds** [comment]
I haven't tested it but yeah you should be able to do that by setting both [positioning](https://github.com/lukechilds/merge-images#positioning) and [dimensions](https://github.com/lukechilds/merge-images#dimensions).
