### ISSUE TITLE
getting "window is not defined" error with nodejs.

### ISSUE THREAD

**Issue by shashank519** [lukechilds/merge-images#79]
> Getting "ReferenceError: window is not defined" when using with nodejs. Below given is my approach.

```
var mergeImages = require("merge-images");

mergeImages([
 { src: image1.buffer },
 { src: image2.buffer }
]).then(b64 => {
 console.log(b64);
});

**Comment by kapil-joshi** [comment]
Yes even I'm getting this issue.
But in the readme docs it says this works with NodeJs.

Can someone please advise.

Thanks.

**Comment by kapil-joshi** [comment]
Actually, i changed my code as below:
```

const imgMerge = require("merge-images"); 
const nodeCanvas = require('canvas').Canvas;

const img1 = 'data:image/jpeg;base64,/9j/4AAQSkZJRgAB........';
const img2 = 'data:image/jpeg;base64,/9j/4AAQSkZJRgAB........';
const img3 = 'data:image/jpeg;base64,/9j/4AAQSkZJRgAB........';

return imgMerge([{ src: new Image(img1), x: 0, y: 0 },
          { src: new Image(img2), x: 100, y: 0 },
          { src: new Image(img3), x: 500, y: 0 }], {Canvas: nodeCanvas})
          .then(b64 => agent.add(new Image(b64)));

```
But getting an error:

**Image is not a constructor**
    at /srv/node_modules/merge-images/dist/index.umd.js:39:13
    at new Promise (<anonymous>)
    at /srv/node_modules/merge-images/dist/index.umd.js:32:54
    at Array.map (<anonymous>)
    at /srv/node_modules/merge-images/dist/index.umd.js:32:23
    at new Promise (<anonymous>)
    at mergeImages (/srv/node_modules/merge-images/dist/index.umd.js:21:9)

Some one please help asap.

Thanks,
Kapil

**Comment by RedSparr0w** [comment]
You can solve this by using:
```js
const mergeImages = require('merge-images');
const { Canvas, Image } = require('canvas');
 
mergeImages(['./body.png', './eyes.png', './mouth.png'], {
  Canvas: Canvas,
  Image: Image
}).then(b64 => ...);
```

Info from the readme here:
https://www.npmjs.com/package/merge-images#nodejs-usage

**Comment by JesseWeb** [comment]
Image field doesn't exist in @type/merge-images while using typescript.plz update it

**Comment by RedSparr0w** [comment]
You get Image from canvas
