### ISSUE TITLE
CORS issue 

### ISSUE THREAD

**Issue by nalnir** [lukechilds/merge-images#80]
I am trying to merge two images from my firebase storage. I allowed cors on my bucket, but when trying to merge it I get: 
Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

I'm not sure if I understand correctly, but shouldn't images from my firebase storage bucket be from the same domain?
Not sure why I get this error

**Comment by donmb1** [comment]
+1
Getting this with hosted images on AWS S3. I have CORS enabled.

**Comment by trevorblades** [comment]
@nalnir @donmb1 I put together a PR (#82) that introduces a `crossOrigin` option so that you can load cross-origin images from CORS-enabled servers as described [in this MDN article](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image).

**Comment by mwmw7** [comment]
@trevorblades thank you.
your code saves my time and effort, but your PR is not merged right now 
So I just clone your repository and make "npm pack" for my project.
I think #82 should be merged as soon as possible

**Comment by donmb1** [comment]
Hi folks,
I have also forked this repo with a solution, you can find it here:
https://github.com/donmb1/merge-images

I didn't do it as "complex" as @trevorblades - in my code I just added this `crossOrigin` piece:

> var img = new Image();
> img.crossOrigin = "Anonymous";
> img.onerror = function () { return reject(new Error('Couldn\'t load image')); };
> img.onload = function () { return resolve(Object.assign({}, source, { img: img })); };
> img.src = source.src;

so it is not configurable for the user. It works fantastic for my purpose.

**Comment by lukechilds** [comment]
#82 is now merged and published as `merge-images@1.2.0`.

**Comment by mwmw7** [comment]
@lukechilds  thanks
