### ISSUE TITLE
Image field doesn't exist in @type/merge-images while using typescript.plz update it

### ISSUE THREAD

**Issue by JesseWeb** [lukechilds/merge-images#88]
Image field doesn't exist in @type/merge-images while using typescript.plz update it

**Comment by lukechilds** [comment]
This project doesn't support TypeScript. If there's an error with the DefinitelyTyped types please open an issue/PR over there.

**Comment by JesseWeb** [comment]
can I write a d.ts file and open a PR for enhancement?

**Comment by lukechilds** [comment]
Thanks for the offer but I'm not really interested in maintaining type definitions, if you want to update the types then I'd recommend just opening a PR  at https://github.com/DefinitelyTyped/DefinitelyTyped.
