### ISSUE TITLE
Test broken

### ISSUE THREAD

**Issue by RuiSiang** [lukechilds/merge-images#90]
Saw drqwerty coming up with a nice rotate option PR #84 , but it doesn't seem to merge properly. Any updates on that? Should be a problem with canvas installation. Thanks
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
```
Should be a problem with .travis.yml

**Comment by lukechilds** [comment]
merge-images has changed since that PR was open. We only support node-canvas v2 now.

The PR will need to be rebased from master before being merged.
