### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by Aiixu** [lukechilds/merge-images#93]
Hey,
Can't figure out why i got this

![image](https://user-images.githubusercontent.com/48332663/82919430-4fae4600-9f76-11ea-9f2d-3bc22d876a82.png)

my code is just 
```js
const mergeImages = require("merge-images");

mergeImages(...); // of course i didn't wrote ... but you understood ^^
````

**Comment by lukechilds** [comment]
Did you read the readme?

https://github.com/lukechilds/merge-images#nodejs-usage

**Comment by lucaspojo** [comment]
Same ^^

**Comment by irothenbaum** [comment]
I'm also getting window is not defined.
I have 
`
const mergeImages = require('merge-images')
const {Image, Canvas} = require('canvas')
`
at the top of my file per the nodejs-usage documentation.

**Comment by lukechilds** [comment]
@lucaspojo did you read the readme?

https://github.com/lukechilds/merge-images#nodejs-usage
